//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal_Analysis
    {
        public int analysis_code { get; set; }
        public System.DateTime analysis_date { get; set; }
        public int weight { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Health_Status Health_Status { get; set; }
    }
}
