//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeding_Time
    {
        public System.DateTime f_time { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Animal Animal { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
