//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zoo_Information
    {
        public string zoo_name { get; set; }
        public string address { get; set; }
        public int zoo_area { get; set; }
        public System.DateTime opening_time { get; set; }
        public System.DateTime closing_time { get; set; }
        public string hotline_phone { get; set; }
        public string zoo_history { get; set; }
    }
}
