//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooModelContainer : DbContext
    {
        public ZooModelContainer()
            : base("name=ZooModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Food> FoodSet { get; set; }
        public virtual DbSet<Food_Ration> Food_RationSet { get; set; }
        public virtual DbSet<Speties> SpetiesSet { get; set; }
        public virtual DbSet<Feeding_Time> Feeding_TimeSet { get; set; }
        public virtual DbSet<Animal> AnimalSet { get; set; }
        public virtual DbSet<Aviary> AviarySet { get; set; }
        public virtual DbSet<Health_Status> Health_StatusSet { get; set; }
        public virtual DbSet<Animal_Analysis> Animal_AnalysisSet { get; set; }
        public virtual DbSet<Zoo_Information> Zoo_InformationSet { get; set; }
        public virtual DbSet<Authorization> AuthorizationSet { get; set; }
        public virtual DbSet<Employee> EmployeeSet { get; set; }
        public virtual DbSet<History_Work_Shift> History_Work_ShiftSet { get; set; }
        public virtual DbSet<Work_Shift> Work_ShiftSet { get; set; }
        public virtual DbSet<Cashbox_Status> Cashbox_StatusSet { get; set; }
        public virtual DbSet<Status_Changes> Status_ChangesSet { get; set; }
        public virtual DbSet<Cashbox> CashboxSet { get; set; }
        public virtual DbSet<Ticket> TicketSet { get; set; }
        public virtual DbSet<Ticket_Type> Ticket_TypeSet { get; set; }
        public virtual DbSet<Job> JobSet { get; set; }
    }
}
